-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 11:27:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema moviedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviedb` DEFAULT CHARACTER SET utf8mb3 ;
USE `moviedb` ;

-- -----------------------------------------------------
-- Table `moviedb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`movie` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  `popularity` INT NULL DEFAULT NULL,
  `runtime` INT NULL DEFAULT NULL,
  `budget` INT NULL DEFAULT NULL,
  `revenue` INT NULL DEFAULT NULL,
  `overview` VARCHAR(300) NULL DEFAULT NULL,
  `release_date` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `homepage` VARCHAR(128) NULL DEFAULT NULL,
  `tagline` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname1` VARCHAR(30) NOT NULL,
  `surname2` VARCHAR(30) NULL DEFAULT NULL,
  `gender` CHAR(1) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`character` (
  `character_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname1` VARCHAR(30) NULL DEFAULT NULL,
  `surname2` VARCHAR(30) NULL DEFAULT NULL,
  `movie_id` INT NOT NULL,
  `person_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`character_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_character`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `person_id_character`
    FOREIGN KEY (`person_id`)
    REFERENCES `moviedb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`keyword` (
  `keyword_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`keyword_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`language_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`role` (
  `role_id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `permission` INT NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `permission_UNIQUE` (`permission` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(25) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `moviedb`.`role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`likedmovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`likedmovie` (
  `movie_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_liked_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id_liked_movie`
    FOREIGN KEY (`user_id`)
    REFERENCES `moviedb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`productioncompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`productioncompany` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`moviecompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`moviecompany` (
  `company_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`company_id`, `movie_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `moviedb`.`productioncompany` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `movie_id_company`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`productioncountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`productioncountry` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`moviecountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`moviecountry` (
  `movie_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `country_id`),
  INDEX `movie_id` (`movie_id` ASC, `country_id` ASC) VISIBLE,
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `moviedb`.`productioncountry` (`country_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `movie_id_country`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`moviecrew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`moviecrew` (
  `person_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `job` VARCHAR(45) NOT NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `person_id_movie_crew_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_movie_crew`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `person_id_movie_crew`
    FOREIGN KEY (`person_id`)
    REFERENCES `moviedb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`moviegenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`moviegenre` (
  `genre_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`genre_id`, `movie_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `moviedb`.`genre` (`genre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `movie_id_genre`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`moviekeyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`moviekeyword` (
  `keyword_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`keyword_id`, `movie_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `keyword_id`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `moviedb`.`keyword` (`keyword_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`movielanguage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`movielanguage` (
  `language_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`language_id`, `movie_id`),
  INDEX `language_id` (`language_id` ASC) VISIBLE,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `language_id`
    FOREIGN KEY (`language_id`)
    REFERENCES `moviedb`.`language` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `movie_id_language`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`review` (
  `movie_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `score` INT NOT NULL,
  `text` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_review`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id_review`
    FOREIGN KEY (`user_id`)
    REFERENCES `moviedb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `moviedb`.`savedmovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`savedmovie` (
  `movie_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `movie_id_saved_movie`
    FOREIGN KEY (`movie_id`)
    REFERENCES `moviedb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id_saved_movie`
    FOREIGN KEY (`user_id`)
    REFERENCES `moviedb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
